AllCops:
  Exclude:
    - '**/config.ru'
    - '**/Rakefile'
    - 'db/**/*'
    - 'bin/*'
    - 'config/**/*'
  DisplayCopNames: true

# FIXME
Metrics/AbcSize:
  Max: 999
  Exclude:
    - 'test/config/locales_test.rb'
    - 'test/test_helper.rb'

 # FIXME
Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
  Max: 999

 # FIXME
Metrics/ClassLength:
  Exclude:
    - 'test/**/*'
  Max: 999

# FIXME
Metrics/CyclomaticComplexity:
  Max: 999
  Exclude:
    - 'test/test_helper.rb'

Metrics/LineLength:
  Max: 80
  IgnoredPatterns:
    - '^\s*#.*'
  Exclude:
    - 'test/**/*'

# FIXME
Metrics/MethodLength:
  Max: 999

# FIXME
Metrics/ModuleLength:
  Max: 999

# FIXME
Metrics/PerceivedComplexity:
  Max: 999
  Exclude:
    - 'test/test_helper.rb'

# render ... and return
Style/AndOr:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

# FIXME
Security/Eval:
  Enabled: false

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: compact

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
