default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: <%= ENV["DB_USERNAME"] %>_development

test:
  <<: *default
  database: <%= ENV["DB_USERNAME"] %>_test

production:
  <<: *default
  database: <%= ENV["DB_USERNAME"] %>_production
